// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hwReservationInfo() {
    driver.get("http://localhost:8080/home/home");
    driver.findElement(By.name("resCode")).click();
    driver.findElement(By.name("resCode")).sendKeys("abcdef");
    driver.findElement(By.name("resCode")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("reservationInfo"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void hwCancelReservation() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("resCode")).click();
    driver.findElement(By.name("resCode")).sendKeys("abcdef");
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.id("cancel")).click();
    {
      WebElement element = driver.findElement(By.id("cancel"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("alterationCode")).click();
    driver.findElement(By.id("alterationCode")).sendKeys("abcdefg");
    driver.findElement(By.cssSelector(".btn-danger:nth-child(2)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void hwChooseSeat() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("tripCode")).click();
    vars.put("oldSeat", driver.findElement(By.id("seat")).getAttribute("value"));
    driver.findElement(By.id("s21")).click();
    driver.findElement(By.id("seat")).click();
    vars.put("newSeat", driver.findElement(By.id("seat")).getAttribute("value"));
    vars.put("price", driver.findElement(By.id("price")).getAttribute("value"));
    driver.findElement(By.id("s14")).click();
    vars.put("newPrice", driver.findElement(By.id("price")).getAttribute("value"));
    driver.findElement(By.id("s27")).click();
    vars.put("oldSeat", driver.findElement(By.id("seat")).getAttribute("value"));
    driver.findElement(By.id("s27")).click();
    vars.put("newSeat", driver.findElement(By.id("seat")).getAttribute("value"));
  }
  @Test
  public void hwMakeReservation() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("resCode")).click();
    driver.findElement(By.name("resCode")).click();
    driver.findElement(By.name("resCode")).click();
    {
      WebElement element = driver.findElement(By.name("resCode"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("tripCode")).click();
    driver.findElement(By.id("buy")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Alex R");
    driver.findElement(By.id("nif")).click();
    driver.findElement(By.id("nif")).sendKeys("123456789");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("abc@abc.abc");
    driver.findElement(By.id("card")).click();
    driver.findElement(By.id("card")).sendKeys("1234 5678 9123 4567");
    driver.findElement(By.name("cardNumber")).click();
    driver.findElement(By.name("cardNumber")).sendKeys("Alex R");
    driver.findElement(By.id("exp")).click();
    driver.findElement(By.id("exp")).sendKeys("12/24");
    driver.findElement(By.id("cvv")).click();
    driver.findElement(By.id("cvv")).sendKeys("123");
    driver.findElement(By.id("buy")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-info"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert-success"));
      assert(elements.size() > 0);
    }
  }
}
